spring:
  application:
    name: couple
  # 导入敏感配置文件
  config:
    import: optional:classpath:application-dev.properties
#  邮箱配置
  mail :
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    host: ${spring.mail.host}

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 从application-secret.properties引用
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver


  data:
    redis:
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml  # XML映射文件位置
  type-aliases-package: com.xkb.couple.pojo.entity  # 实体类包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL日志
    map-underscore-to-camel-case: true  # 自动驼峰命名转换

couple:
  jwt:
    # 从application-secret.properties引用
    secret: ${couple.jwt.secret}
    expiration: 9999999999  # 过期时间，单位：秒
#  验证码
  captcha:
    expiration: 300  # 过期时间，单位：秒
#  邮件配置
  mail:
    fromEmail: ${couple.mail.fromEmail}
    fromName: 情侣小程序平台

