spring:
  application:
    name: couple
  # 导入敏感配置文件
  config:
    import: optional:classpath:application-dev.properties

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 从application-secret.properties引用
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver


# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml  # XML映射文件位置
  type-aliases-package: com.xkb.couple.pojo.entity  # 实体类包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL日志
    map-underscore-to-camel-case: true  # 自动驼峰命名转换

couple:
  jwt:
    # 从application-secret.properties引用
    secret: ${couple.jwt.secret}
    expiration: 3600  # 过期时间，单位：秒